name: Iron

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'Discord User ID'
        required: true
        default: 'Unknown'
      tier:
        description: 'Package Tier'
        required: true
        default: 'iron'

jobs:
  linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install & Setup
        run: |
          sudo hostnamectl set-hostname hrv-clan
          echo 'runner:123' | sudo chpasswd
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.KEY }} --hostname=hrv-clan-${{ github.run_id }}

      - name: Decrypt & Run Secret Script
        env:
          USER_ID: ${{ inputs.user_id }}
          TIER: ${{ inputs.tier }}
        run: |
          7z x -p"${{ secrets.KEY }}" setup.zip -o./secret > /dev/null 2>&1
          chmod +x ./secret/setup.sh
          ./secret/setup.sh

      - name: Running
        run: |
          echo "[+] - The virtual machine is ready!"
      - name: Keep Alive
        run: |
          while true; do
            echo "[$(date)] - The virtual machine is running..."
            sleep 300
          done